Repository wooahan-agile/idu-market-server, pull requests merged in 2021-05, with the labels that each got.

#173 [image] image 관련 API 구현
  app/.eslintrc.json
  app/app.ts
  app/src/apis/image/image.ctrl.ts
  app/src/models/services/Board/Board.ts
  app/src/models/services/Board/BoardStorage.ts
  app/src/models/services/Board/Comment/Comment.ts
  app/src/models/services/Board/Comment/CommentStorage.ts
  app/src/models/services/SaleList/SaleListStorage.ts
Labels: API, 기능 구현, 기획 및 설계

#174 .eslintrc 파일 경로 변경
  app/.eslintrc.json
Labels: 버그

#175 [boards] 게시판 API 구현
  app/src/models/services/Board/Board.ts
  app/src/models/services/Board/BoardStorage.ts
Labels: API, DB, 기능 구현, 서버

#177 [boards] 게시판 API 구현
  app/src/apis/search/search.ctrl.ts
  app/src/models/services/Auth/AuthStorage.ts
  app/src/models/services/Board/Board.ts
  app/src/models/services/Board/BoardStorage.ts
  app/src/models/services/Student/Student.ts
Labels: API, 기능 구현, 기획 및 설계, 서버

#178 [boards] 게시판 API 수정
  app/src/apis/search/search.ctrl.ts
  app/src/models/services/Auth/AuthStorage.ts
  app/src/models/services/Board/Board.ts
  app/src/models/services/Board/BoardStorage.ts
  app/src/models/services/Student/Student.ts
Labels: API, DB, 기능 구현, 배포, 서버

#181 [cors] 백엔드 cors 적용
  app/app.ts
  app/src/models/services/Board/BoardStorage.ts
Labels: 기능 구현

#179 모바일 자유게시판 조회용(게시판 내용 데이터 추가)
  app/src/models/services/Board/BoardStorage.ts
Labels: API, 기능 구현

#182 [login] 로그인 API 구현
  app/app.ts
  app/src/apis/root/root.ctrl.ts
  app/src/models/services/Student/Student.ts
Labels: API, 기능 구현, 기획 및 설계, 서버

#193 [Typescript] 게시판 1 증가 시 게시판 조회수 반환
  app/app.ts
  app/src/models/services/Board/Board.ts
  app/src/models/services/Board/BoardStorage.ts
Labels: API, 기능 구현

#194 [fix] 조회수 증가 API에서 해당값 반환해주도록 수정
  app/app.ts
  app/src/models/services/Board/Board.ts
  app/src/models/services/Board/BoardStorage.ts
Labels: API

#196 CORS 테스트
  app/app.ts
  app/src/models/services/Board/BoardStorage.ts
Labels: 기능 구현

#197 Refactor(soongu/cors): header에 access-control-allow-origin 추가
  app/app.ts
Labels: API, 기능 구현

#199 [purchaselists] 구매목록 API 구현
  app/src/models/services/Board/Comment/Comment.ts
  app/src/models/services/Board/Comment/CommentStorage.ts
Labels: API, 기능 구현, 기획 및 설계, 서버

#201 [mariaDB] MySQL -> MariaDB로 변경
  app/.eslintrc.json
  app/app.ts
  app/package-lock.json
  app/package.json
  app/src/apis/boards/commemt.ctrl.ts
  app/src/apis/watch-list/index.ts
  app/src/apis/watch-list/watch-list.ctrl.ts
  app/src/config/mariadb.ts
  app/src/models/services/Board/Board.ts
  app/src/models/services/Board/BoardStorage.ts
  app/src/models/services/Board/Comment/Comment.ts
  app/src/models/services/Board/Comment/CommentStorage.ts
  app/src/models/services/Email/Email.ts
  app/src/models/services/Profile/Profile.ts
  app/src/models/services/Profile/ProfileStorage.ts
  app/src/models/services/PurchaseList/PurchaseList.ts
  app/src/models/services/PurchaseList/PurchaseListStorage.ts
  app/src/models/services/SaleList/SaleList.ts
  app/src/models/services/SaleList/SaleListStorage.ts
  app/src/models/services/Student/Student.ts
  app/src/models/services/Student/StudentStorage.ts
  app/src/models/services/WatchList/WatchList.ts
  app/src/models/services/WatchList/WatchListStorage.ts
Labels: API, DB, 기능 구현, 서버

#203 [image] image 관련 API 구현
  app/src/apis/image/image.ctrl.ts
  app/src/middlewares/s3.ts
Labels: API, 기능 구현, 서버

#205 [inquiry] 문의 API 구현
  app/app.ts
  app/src/apis/inquiry/index.ts
  app/src/apis/inquiry/inquiry.ctrl.ts
  app/src/models/services/Email/Email.ts
  app/src/models/services/Inquiry/InquiryStorage.ts
Labels: API, 기능 구현, 기획 및 설계, 서버

#208 [inquiry] 문의 API 구현
  app/src/models/services/Email/Email.ts
  app/src/models/services/Student/StudentStorage.ts
Labels: API, 기능 구현, 기획 및 설계, 서버

#210 [Notifications] 알람 기능 구현 완료 #191
  app/app.ts
  app/src/apis/notification/index.ts
  app/src/apis/notification/notification.ctrl.ts
  app/src/models/services/Board/Comment/Comment.ts
  app/src/models/services/Email/Email.ts
  app/src/models/services/Notification/Notification.ts
  app/src/models/services/Notification/NotificationStorage.ts
  app/src/models/services/PurchaseList/PurchaseList.ts
Labels: API, DB, 기능 구현, 서버

#211 [image] 이미지 관련 API 구현
  app/src/apis/image/image.ctrl.ts
Labels: API, 기능 구현, 기획 및 설계, 서버

#212 modify(soongu/auth): jwt 닉네임 정보 추가
  app/src/models/services/Auth/Auth.ts
Labels: 기능 구현

#213 modify(soongu/auth): id 조회 데이터추가
  app/src/models/services/Student/StudentStorage.ts
Labels: 기능 구현

#214 modify(soongu/notifications): 알림 조회 url 데이터 추가 #191
  app/src/models/services/Notification/Notification.ts
  app/src/models/services/Notification/NotificationStorage.ts
Labels: 기능 구현

#218 [purchaselists] 구매목록 API 구현
  app/src/models/services/Notification/Notification.ts
  app/src/models/services/Notification/NotificationStorage.ts
  app/src/models/services/PurchaseList/PurchaseList.ts
  app/src/models/services/PurchaseList/PurchaseListStorage.ts
Labels: API, 기능 구현, 기획 및 설계, 서버

#219 [Notifications] 송신인과 수신인이 같다면 알람생성 #191
  app/app.ts
  app/src/apis/boards/board.ctrl.ts
  app/src/apis/boards/commemt.ctrl.ts
  app/src/apis/boards/index.ts
  app/src/apis/image/image.ctrl.ts
  app/src/apis/image/index.ts
  app/src/apis/inquiry/index.ts
  app/src/apis/inquiry/inquiry.ctrl.ts
  app/src/apis/profile/index.ts
  app/src/apis/profile/profile.ctrl.ts
  app/src/apis/purchase-list/index.ts
  app/src/apis/purchase-list/purchase-list.ctrl.ts
  app/src/apis/root/index.ts
  app/src/apis/sale-list/index.ts
  app/src/apis/sale-list/sale-list.ctrl.ts
  app/src/apis/watch-list/index.ts
  app/src/apis/watch-list/watch-list.ctrl.ts
  app/src/config/logger.ts
  app/src/config/mariadb.ts
  app/src/config/types.ts
  app/src/middlewares/auth.ts
  app/src/middlewares/s3.ts
  app/src/models/services/Board/Board.ts
  app/src/models/services/Board/BoardStorage.ts
  app/src/models/services/Board/Comment/Comment.ts
  app/src/models/services/Board/Comment/CommentStorage.ts
  app/src/models/services/Category/Category.ts
  app/src/models/services/Inquiry/InquiryStorage.ts
  app/src/models/services/Notification/Notification.ts
  app/src/models/services/Notification/NotificationStorage.ts
  app/src/models/services/Profile/Profile.ts
  app/src/models/services/Profile/ProfileStorage.ts
  app/src/models/services/SaleList/SaleList.ts
  app/src/models/services/WatchList/WatchList.ts
  app/src/models/services/WatchList/WatchListStorage.ts
  app/src/models/utils/Cryptor.ts
  app/src/models/utils/Error.ts
  app/src/models/utils/String.ts
  app/src/tests/root.spec.js
  app/src/types/express.d.ts
  app/tsconfig.json
Labels: 기능 구현

#220 modify(soongu/notifications): 불필요한 console 제거
  app/src/models/services/Notification/NotificationStorage.ts
Labels: 기능 구현

#221 [comments] 댓글 API 구현
  app/src/models/services/Board/Board.ts
  app/src/models/services/Board/Comment/Comment.ts
  app/src/models/services/Board/Comment/CommentStorage.ts
Labels: API, 기능 구현, 기획 및 설계, 서버

#223 [board] 게시판 api 구현
  app/src/models/services/Board/Board.ts
  app/src/models/services/Board/BoardStorage.ts
Labels: API, 기능 구현, 기획 및 설계, 서버

#224 [Students] 비밀번호 변경 시 hash, salt값 변경
  app/src/models/services/Student/Student.ts
  app/src/models/services/Student/StudentStorage.ts
  app/src/views/reset-password.ejs
Labels: 기능 구현

#225 [Notifications] 불필요한 코드 제거
  app/package-lock.json
  app/src/apis/notification/index.ts
  app/src/apis/notification/notification.ctrl.ts
  app/src/models/services/Email/Email.ts
  app/src/models/services/Notification/NotificationStorage.ts
Labels: 기능 구현

#226 [log] log 시간 현재 환경 표준시간으로 변경
  app/package-lock.json
  app/package.json
  app/src/config/logger.ts
Labels: 기능 구현, 기획 및 설계, 서버

#227 cors 옵션 적용 #180
  app/app.ts
Labels: 기능 구현

#228 [Notifications] 알람 조회시 상위 20개 데이터만 반환
  app/src/models/services/Notification/NotificationStorage.ts
Labels: 기능 구현

#229 [boards] 게시판 API 구현
  app/app.ts
  app/src/models/services/Board/BoardStorage.ts
  app/src/models/services/Board/Comment/Comment.ts
  app/src/models/services/Board/Comment/CommentStorage.ts
Labels: API, 기능 구현, 기획 및 설계, 서버

#230 [notiTable] 사용자의 중요 활동이 저장될 알림(공지) API 구현
  app/src/models/services/Notification/Notification.ts
  app/src/models/services/Notification/NotificationStorage.ts
Labels: API, 기능 구현, 서버

#233 [salelist] 판매목록 api 구현
  app/src/models/services/SaleList/SaleListStorage.ts
Labels: API, 기능 구현, 기획 및 설계, 서버

#234 [notiTable] 사용자의 중요 활동이 저장될 알림(공지) API 구현
  app/src/apis/image/image.ctrl.ts
  app/src/models/services/Notification/NotificationStorage.ts
Labels: API, 기능 구현, 기획 및 설계, 서버
