Repository wooahan-agile/idu-market-server, pull requests merged in 2021-03, with the labels that each got.

#41 [hotfix] 각종 오류 해결
  app/app.js
  app/src/apis/root/index.js
  app/src/apis/root/root.ctrl.js
  app/src/models/services/Auth.js
  app/src/models/services/AuthStorage.js
  app/src/models/services/Email.js
  app/src/models/services/User.js
  app/src/models/services/UserStorage.js
  app/src/models/utils/Cryptor.js
Labels: 버그, 서버

#44 [changeUI] 비밀번호 변경하는 UI 수정
  app/src/public/css/reset-password.css
  app/src/views/reset-password.ejs
Labels: 서버

#45 충돌상황 해결
  app/app.js
  app/src/apis/root/index.js
  app/src/apis/root/root.ctrl.js
  app/src/models/services/Auth.js
  app/src/models/services/AuthStorage.js
  app/src/models/services/Email.js
  app/src/models/services/User.js
  app/src/models/services/UserStorage.js
  app/src/models/utils/Cryptor.js
  app/src/public/css/reset-password.css
  app/src/views/reset-password.ejs
Labels: 버그

#46 [watchlist] 관심목록 API 구현
  app/.babelrc
  app/app.js
  app/bin/www.js
  app/package-lock.json
  app/package.json
  app/src/apis/view/index.js
  app/src/apis/watchlist/routes.js
  app/src/apis/watchlist/watchList.ctrl.js
  app/src/config/db.js
  app/src/config/mail.js
  app/src/middlewares/auth.js
  app/src/models/services/Auth.js
  app/src/models/services/AuthStorage.js
  app/src/models/services/Email.js
  app/src/models/services/User.js
  app/src/models/services/UserStorage.js
  app/src/models/services/watchlist/WatchList.js
  app/src/models/services/watchlist/WatchListStorage.js
  app/src/models/utils/WooahanDate.js
  app/src/public/js/reset-password.js
  app/src/views/reset-password.ejs
Labels: API, 기능 구현, 서버

#48 [Boards] 게시판 API 구현
  app/.babelrc
  app/app.js
  app/bin/www.js
  app/package-lock.json
  app/package.json
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/index.js
  app/src/apis/view/index.js
  app/src/apis/watchlist/routes.js
  app/src/apis/watchlist/watchList.ctrl.js
  app/src/config/db.js
  app/src/config/mail.js
  app/src/middlewares/auth.js
  app/src/models/services/Auth.js
  app/src/models/services/AuthStorage.js
  app/src/models/services/Email.js
  app/src/models/services/UserStorage.js
  app/src/models/services/boards/Board.js
  app/src/models/services/boards/BoardCode.js
  app/src/models/services/boards/BoardStorage.js
  app/src/models/services/watchlist/WatchList.js
  app/src/models/services/watchlist/WatchListStorage.js
  app/src/models/utils/WooahanDate.js
  app/src/public/js/reset-password.js
  app/src/views/reset-password.ejs
Labels: API, 서버

#53 Fix(woorim/hotfix): Auth SQL 에러 해결
  app/src/models/services/Auth/AuthStorage.js
Labels: 버그, 서버

#59 로그인 성공시 user의 id도 반환하도록 추가
  app/src/models/services/User/User.js
Labels: API, 기능 구현, 서버

#63 [watchlist] 관심목록 API 구현
  app/src/models/services/watchlist/WatchListStorage.js
Labels: DB

#56 [purchaselists] 구매목록 조회, 생성 api 구현
  app/app.js
  app/package-lock.json
  app/package.json
  app/src/apis/purchaseList/purchaseList.ctrl.js
  app/src/apis/purchaseList/routes.js
  app/src/apis/root/index.js
  app/src/apis/root/root.ctrl.js
  app/src/apis/view/index.js
  app/src/config/db.js
  app/src/config/mail.js
  app/src/middlewares/auth.js
  app/src/models/services/Auth.js
  app/src/models/services/AuthStorage.js
  app/src/models/services/Email.js
  app/src/models/services/User.js
  app/src/models/services/UserStorage.js
  app/src/models/services/purchaselist/PurchaseList.js
  app/src/models/services/purchaselist/PurchaseListStorage.js
  app/src/models/utils/Cryptor.js
  app/src/models/utils/WooahanDate.js
  app/src/public/js/reset-password.js
  app/src/views/reset-password.ejs
Labels: API, 기능 구현, 기획 및 설계, 서버

#65 [image] image 관련 API 구현
  app/app.js
  app/package-lock.json
  app/package.json
  app/src/apis/image/image.ctrl.js
  app/src/apis/image/routes.js
  app/src/middlewares/upload.js
  app/src/models/services/User.js
  app/src/models/services/UserStorage.js
  app/src/models/services/image/Image.js
  app/src/models/services/image/ImageStorage.js
  app/src/views/reset-password.ejs
Labels: 기능 구현, 기획 및 설계

#67 [boards] 게시판 API 초기 구현 및 boardCode -> Catygory로 변경
  app/.eslintrc.js
  app/app.js
  app/package-lock.json
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/index.js
  app/src/models/services/boards/Board.js
  app/src/models/services/boards/BoardStorage.js
  app/src/models/services/categories/Category.js
Labels: API, 기능 구현, 서버

#68 [watchlist] 관심목록 API 구현
  .github/ISSUE_TEMPLATE/---------.md
  .github/ISSUE_TEMPLATE/api--------.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  app/package-lock.json
  app/src/apis/watchlist/watch-list.ctrl.js
  app/src/models/services/watchlist/WatchList.js
  app/src/models/services/watchlist/WatchListStorage.js
  app/src/public/css/reset-password.css
Labels: API, DB, 기획 및 설계

#73 폴더명 변경 및 index router 경로 수정
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/index.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Category/Category.js
Labels: 기능 구현, 서버

#74 [image] image 관련 API 구현
  app/app.js
  app/src/apis/image/routes.js
  app/src/models/services/image/Image.js
Labels: 기능 구현, 기획 및 설계

#75 [image] image 관련 API 구현
  app/app.js
  app/package-lock.json
  app/package.json
  app/src/apis/image/image.ctrl.js
  app/src/apis/image/routes.js
  app/src/middlewares/upload.js
  app/src/models/services/User.js
  app/src/models/services/UserStorage.js
  app/src/models/services/image/Image.js
  app/src/models/services/image/ImageStorage.js
  app/src/views/reset-password.ejs
Labels: API, 서버

#79 SQL price 필드 추가 및 utils 폴더에 String 파일 추가
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/utils/String.js
Labels: 기능 구현, 서버

#80 [salelists] 판매목록 조회, 생성 api 구현
  app/app.js
  app/src/apis/sale-list/routes.js
  app/src/apis/sale-list/sale-list.ctrl.js
  app/src/models/services/saleList/SaleList.js
  app/src/models/services/saleList/SaleListStorage.js
Labels: API, 기능 구현, 기획 및 설계, 서버

#82 [image] image 관련 API 구현
  .github/ISSUE_TEMPLATE/---------.md
  .github/ISSUE_TEMPLATE/api--------.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  app/app.js
  app/package-lock.json
  app/package.json
  app/src/apis/image/image.ctrl.js
  app/src/apis/image/routes.js
  app/src/middlewares/upload.js
  app/src/models/services/saleList/SaleListStorage.js
Labels: 기능 구현, 기획 및 설계

#83 [image] image 관련 API 구현
  app/package-lock.json
  app/package.json
  app/src/apis/image/image.ctrl.js
  app/src/apis/image/routes.js
  app/src/middlewares/s3.js
  app/src/middlewares/upload.js
Labels: 기능 구현, 기획 및 설계

#84 [search] 검색 API 설계 및 구현
  .gitignore
  app/app.js
  app/src/apis/image/index.js
  app/src/apis/purchase-list/index.js
  app/src/apis/sale-list/index.js
  app/src/apis/search/index.js
  app/src/apis/search/search.ctrl.js
  app/src/apis/watch-list/index.js
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Email/Email.js
  app/src/models/services/User.js
  app/src/models/services/UserStorage.js
Labels: API, 기능 구현, 서버

#85 게시판 수정 API 최적화
  app/app.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
Labels: API, 서버

#86 검색 메서드의 SQL 수정
  app/src/models/services/Board/BoardStorage.js
Labels: DB, 서버

#88 [image] image 관련 API 구현
  app/src/apis/image/image.ctrl.js
  app/src/middlewares/s3.js
Labels: 기능 구현, 기획 및 설계

#89 [notification] 메일 알림 API 설계 및 구현 #87
  app/app.js
  app/src/apis/notification/index.js
  app/src/apis/notification/notification.ctrl.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Email/Email.js
  app/src/models/services/User/UserStorage.js
Labels: API, 기능 구현, 서버

#90 [profile] 프로필 API 구현
  .gitignore
  app/.babelrc
  app/.eslintrc.js
  app/app.js
  app/bin/www.js
  app/src/apis/image/index.js
  app/src/apis/profile/index.js
  app/src/apis/profile/profile.ctrl.js
  app/src/apis/purchase-list/index.js
  app/src/apis/purchase-list/purchase-list.ctrl.js
  app/src/apis/sale-list/index.js
  app/src/apis/sale-list/sale-list.ctrl.js
  app/src/apis/search/index.js
  app/src/apis/search/search.ctrl.js
  app/src/apis/watch-list/index.js
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/models/services/Category/Category.js
  app/src/models/services/PurchaseList/PurchaseList.js
  app/src/models/services/PurchaseList/PurchaseListStorage.js
  app/src/models/services/User.js
  app/src/models/services/User/User.js
  app/src/models/services/UserStorage.js
  app/src/models/services/image/Image.js
  app/src/models/services/image/ImageStorage.js
  app/src/models/services/profile/Profile.js
  app/src/models/services/profile/ProfileStorage.js
  app/src/models/services/saleList/SaleList.js
  app/src/models/services/saleList/SaleListStorage.js
  app/src/models/utils/String.js
  app/src/public/css/reset-password.css
  app/src/views/reset-password.ejs
Labels: API, 기능 구현, 기획 및 설계

#92 [redis] 비번 찾기 Token 저장 DB로 Redis 적용
  app/package-lock.json
  app/package.json
  app/src/apis/root/root.ctrl.js
  app/src/models/services/Auth/Auth.js
  app/src/models/services/Auth/AuthStorage.js
  app/src/models/services/Email/Email.js
  app/src/models/services/User/User.js
  app/src/models/utils/WooahanDate.js
  app/src/public/js/reset-password.js
Labels: DB, 기능 구현, 서버

#95 [Boards] develop 머지 충돌 해결 및 댓글 기능 추가
  app/package-lock.json
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/commemt.ctrl.js
  app/src/apis/boards/index.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
Labels: API, 기능 구현, 서버

#97 [boards] 무한 스크롤을 위한 개수 제한 및 리펙토링
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
Labels: API, 서버

#99 [boards] 게시판 API 구현
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/index.js
  app/src/apis/profile/index.js
  app/src/apis/profile/profile.ctrl.js
  app/src/apis/purchase-list/index.js
  app/src/apis/purchase-list/purchase-list.ctrl.js
  app/src/apis/sale-list/index.js
  app/src/apis/sale-list/sale-list.ctrl.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/SaleList/SaleList.js
  app/src/models/services/SaleList/SaleListStorage.js
  app/src/models/services/profile/Profile.js
  app/src/models/services/profile/ProfileStorage.js
Labels: API, 기능 구현, 기획 및 설계

#100 [purchaselists] 구매목록 API 구현
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/index.js
  app/src/apis/purchase-list/index.js
  app/src/apis/purchase-list/purchase-list.ctrl.js
  app/src/apis/sale-list/index.js
  app/src/apis/sale-list/sale-list.ctrl.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/PurchaseList/PurchaseList.js
  app/src/models/services/PurchaseList/PurchaseListStorage.js
  app/src/models/services/SaleList/SaleList.js
Labels: API, 기능 구현, 기획 및 설계

#106 Merge(woorim/develop): Master와 첫 병합 테스트
  .github/ISSUE_TEMPLATE/---------.md
  .github/ISSUE_TEMPLATE/api--------.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  app/.babelrc
  app/.eslintrc.js
  app/app.js
  app/bin/www.js
  app/package-lock.json
  app/package.json
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/commemt.ctrl.js
  app/src/apis/boards/index.js
  app/src/apis/image/image.ctrl.js
  app/src/apis/image/index.js
  app/src/apis/notification/index.js
  app/src/apis/notification/notification.ctrl.js
  app/src/apis/profile/index.js
  app/src/apis/profile/profile.ctrl.js
  app/src/apis/purchase-list/index.js
  app/src/apis/purchase-list/purchase-list.ctrl.js
  app/src/apis/root/index.js
  app/src/apis/root/root.ctrl.js
  app/src/apis/sale-list/index.js
  app/src/apis/sale-list/sale-list.ctrl.js
  app/src/apis/search/index.js
  app/src/apis/search/search.ctrl.js
  app/src/apis/view/index.js
  app/src/apis/watch-list/index.js
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/config/db.js
  app/src/config/mail.js
  app/src/middlewares/auth.js
  app/src/middlewares/s3.js
  app/src/models/services/Auth/Auth.js
  app/src/models/services/Auth/AuthStorage.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Category/Category.js
  app/src/models/services/Email/Email.js
  app/src/models/services/Image/Image.js
  app/src/models/services/Image/ImageStorage.js
  app/src/models/services/Profile/Profile.js
  app/src/models/services/Profile/ProfileStorage.js
  app/src/models/services/PurchaseList/PurchaseList.js
  app/src/models/services/PurchaseList/PurchaseListStorage.js
  app/src/models/services/SaleList/SaleList.js
  app/src/models/services/SaleList/SaleListStorage.js
  app/src/models/services/User/User.js
  app/src/models/services/User/UserStorage.js
  app/src/models/services/watchlist/WatchList.js
  app/src/models/services/watchlist/WatchListStorage.js
  app/src/models/utils/Cryptor.js
  app/src/models/utils/String.js
  app/src/public/css/reset-password.css
  app/src/public/js/reset-password.js
  app/src/views/reset-password.ejs
Labels: 배포

#111 [기능] 로그 관리
  .github/ISSUE_TEMPLATE/api--------.md
  app/app.js
  app/bin/www.js
  app/package-lock.json
  app/package.json
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/commemt.ctrl.js
  app/src/apis/image/image.ctrl.js
  app/src/apis/notification/notification.ctrl.js
  app/src/apis/profile/profile.ctrl.js
  app/src/apis/purchase-list/purchase-list.ctrl.js
  app/src/apis/root/root.ctrl.js
  app/src/apis/sale-list/sale-list.ctrl.js
  app/src/apis/search/search.ctrl.js
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/config/logger.js
  app/src/models/services/Image/ImageStorage.js
Labels: 기능 구현, 기획 및 설계

#112 [watchlist] 관심목록 API 구현
  app/src/models/services/watchlist/WatchListStorage.js
Labels: API, 기능 구현, 기획 및 설계, 서버

#115 [profile] 프로필 API 구현
  app/app.js
  app/package.json
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/commemt.ctrl.js
  app/src/apis/boards/index.js
  app/src/apis/image/image.ctrl.js
  app/src/apis/notification/index.js
  app/src/apis/notification/notification.ctrl.js
  app/src/apis/profile/index.js
  app/src/apis/profile/profile.ctrl.js
  app/src/apis/root/index.js
  app/src/apis/root/root.ctrl.js
  app/src/apis/view/index.js
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/config/db.js
  app/src/config/mail.js
  app/src/middlewares/auth.js
  app/src/middlewares/s3.js
  app/src/models/services/Auth/Auth.js
  app/src/models/services/Auth/AuthStorage.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Email/Email.js
  app/src/models/services/Profile/Profile.js
  app/src/models/services/Profile/ProfileStorage.js
  app/src/models/services/User/UserStorage.js
  app/src/models/utils/Cryptor.js
  app/src/public/js/reset-password.js
Labels: API, 기능 구현, 기획 및 설계, 서버

#116 [profile] 프로필 API 구현
  app/src/models/services/Profile/Profile.js
  app/src/models/services/Profile/ProfileStorage.js
Labels: API, 기능 구현, 기획 및 설계, 서버

#117 [watchlist] 관심목록 API 구현
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/models/services/watchlist/WatchListStorage.js
Labels: API, 기능 구현, 서버

#118 [watchlist] 관심목록 API 구현
  app/package-lock.json
  app/package.json
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/models/services/watchlist/WatchList.js
Labels: API, 기능 구현, 서버

#119 [CICD] 지속적 통합 및 지속적 배포 도입
  app/app.js
  app/bin/www.js
  app/package-lock.json
  app/package.json
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/commemt.ctrl.js
  app/src/apis/boards/index.js
  app/src/apis/image/image.ctrl.js
  app/src/apis/notification/index.js
  app/src/apis/notification/notification.ctrl.js
  app/src/apis/profile/index.js
  app/src/apis/profile/profile.ctrl.js
  app/src/apis/purchase-list/purchase-list.ctrl.js
  app/src/apis/root/index.js
  app/src/apis/root/root.ctrl.js
  app/src/apis/sale-list/sale-list.ctrl.js
  app/src/apis/search/search.ctrl.js
  app/src/apis/view/index.js
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/config/db.js
  app/src/config/logger.js
  app/src/config/mail.js
  app/src/middlewares/auth.js
  app/src/middlewares/s3.js
  app/src/models/services/Auth/Auth.js
  app/src/models/services/Auth/AuthStorage.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Email/Email.js
  app/src/models/services/Image/ImageStorage.js
  app/src/models/services/Profile/Profile.js
  app/src/models/services/Profile/ProfileStorage.js
  app/src/models/services/User/UserStorage.js
  app/src/models/services/WatchList/WatchList.js
  app/src/models/services/WatchList/WatchListStorage.js
  app/src/models/utils/Cryptor.js
  app/src/public/js/reset-password.js
Labels: 배포, 서버

#121 [watchlist] 관심목록 API 구현
  app/src/models/services/WatchList/WatchList.js
Labels: API, 기능 구현, 서버

#122 [CICD] github action 테스트
  .github/workflows/continous-deploy.yml
  app/src/apis/watch-list/index.js
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/models/services/WatchList/WatchList.js
  app/src/models/services/WatchList/WatchListStorage.js
  appspec.yml
  scripts/afterInstall.bash
  scripts/beforeInstall.bash
Labels: 배포, 서버

#123 Docs(woorim/CICD): docker 푸시 액션 이벤트 모듈 v2로 업그레이드
  .github/workflows/continous-deploy.yml
Labels: 배포, 서버

#125 [purchaselists] 구매목록 API 구현
  app/src/models/services/Board/Board.js
  app/src/models/services/PurchaseList/PurchaseList.js
Labels: API, 기능 구현, 서버

#126 Auth의 JWT 응답 페이로드에 profile_path와 admin_flag 추가
  app/src/apis/root/root.ctrl.js
  app/src/models/services/Auth/Auth.js
  app/src/models/services/User/User.js
Labels: 기능 구현, 서버

#128 [purchaselists] 구매목록 API 구현
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/commemt.ctrl.js
  app/src/apis/boards/index.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
Labels: API, 기능 구현, 서버

#127 [Boards] 게시판 상세보기 관심목록 플래그 추가
  app/package-lock.json
  app/package.json
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
Labels: 기능 구현

#129 [purchaselists] 구매목록 API 구현
  app/src/apis/image/image.ctrl.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/PurchaseList/PurchaseList.js
  app/src/models/services/SaleList/SaleList.js
Labels: API, 기능 구현, 서버

#130 [purchaselists] 구매목록 API 구현
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
Labels: API, 기능 구현, 서버

#131 [purchaselists] 구매목록 API 구현
  .gitignore
  app/.babelrc
  app/.eslintrc.js
  app/package-lock.json
  app/package.json
  app/src/models/services/Board/Board.js
  app/src/models/services/Profile/Profile.js
  app/src/models/services/Profile/ProfileStorage.js
  app/src/models/services/PurchaseList/PurchaseListStorage.js
  app/src/models/services/SaleList/SaleListStorage.js
Labels: API, 기능 구현, 서버

#138 Refactor(boards/soongu): 게시판 생성 시 URL 유효성 검사, docs(soongu): 프로젝트 폴더명 변경
  app/src/models/services/Board/Board.js
Labels: 기능 구현

#139 [salelist, purchaselist, watchlist, image, profile] 전체 리펙토링
  .dockerignore
  .github/ISSUE_TEMPLATE/---------.md
  .github/ISSUE_TEMPLATE/api--------.md
  .gitignore
  Dockerfile
  app/package-lock.json
  app/package.json
  app/src/apis/image/image.ctrl.js
  app/src/apis/image/index.js
  app/src/apis/profile/index.js
  app/src/apis/profile/profile.ctrl.js
  app/src/apis/purchase-list/index.js
  app/src/apis/purchase-list/purchase-list.ctrl.js
  app/src/apis/sale-list/index.js
  app/src/apis/sale-list/sale-list.ctrl.js
  app/src/apis/watch-list/index.js
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/models/services/Image/Image.js
  app/src/models/services/Image/ImageStorage.js
  app/src/models/services/PurchaseList/PurchaseList.js
  app/src/models/services/PurchaseList/PurchaseListStorage.js
  app/src/models/services/SaleList/SaleListStorage.js
  app/src/models/services/WatchList/WatchListStorage.js
Labels: API, 기능 구현, 서버

#140 [salelists] 판매목록 API 구현
  app/src/models/services/SaleList/SaleListStorage.js
Labels: API, 기능 구현, 서버

#142 게시판 조회시마다 profile_path도 응답하도록 수정
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/CommentStorage.js
Labels: 기능 구현, 서버

#143 [signup] 회원가입 API 구현
  app/src/apis/profile/index.js
  app/src/apis/profile/profile.ctrl.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Profile/Profile.js
  app/src/models/services/Profile/ProfileStorage.js
  app/src/models/services/PurchaseList/PurchaseList.js
  app/src/models/services/PurchaseList/PurchaseListStorage.js
  app/src/models/services/SaleList/SaleListStorage.js
  app/src/models/services/User/User.js
  app/src/models/services/User/UserStorage.js
  app/src/models/services/WatchList/WatchList.js
Labels: API, 기획 및 설계, 서버

#144 ADD(woorim/CICD): 배포 자동화 설정
  .github/workflows/continous-deploy.yml
  Dockerfile
  appspec.yml
  scripts/afterInstall.bash
  scripts/beforeInstall.bash
Labels: 배포, 서버

#145 배포 자동화 설정
  .dockerignore
  .github/ISSUE_TEMPLATE/---------.md
  .github/ISSUE_TEMPLATE/api--------.md
  .github/workflows/continous-deploy.yml
  .gitignore
  Dockerfile
  app/.babelrc
  app/.eslintrc.js
  app/app.js
  app/package-lock.json
  app/package.json
  app/src/apis/boards/board.ctrl.js
  app/src/apis/boards/commemt.ctrl.js
  app/src/apis/boards/index.js
  app/src/apis/image/image.ctrl.js
  app/src/apis/image/index.js
  app/src/apis/notification/index.js
  app/src/apis/profile/index.js
  app/src/apis/profile/profile.ctrl.js
  app/src/apis/purchase-list/index.js
  app/src/apis/purchase-list/purchase-list.ctrl.js
  app/src/apis/root/index.js
  app/src/apis/sale-list/index.js
  app/src/apis/sale-list/sale-list.ctrl.js
  app/src/apis/search/index.js
  app/src/apis/watch-list/index.js
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/models/services/Auth/AuthStorage.js
  app/src/models/services/Board/Board.js
  app/src/models/services/Board/BoardStorage.js
  app/src/models/services/Board/Comment/Comment.js
  app/src/models/services/Board/Comment/CommentStorage.js
  app/src/models/services/Image/Image.js
  app/src/models/services/Image/ImageStorage.js
  app/src/models/services/Profile/Profile.js
  app/src/models/services/Profile/ProfileStorage.js
  app/src/models/services/PurchaseList/PurchaseList.js
  app/src/models/services/PurchaseList/PurchaseListStorage.js
  app/src/models/services/SaleList/SaleList.js
  app/src/models/services/SaleList/SaleListStorage.js
  app/src/models/services/User/User.js
  app/src/models/services/User/UserStorage.js
  app/src/models/services/WatchList/WatchList.js
  app/src/models/services/WatchList/WatchListStorage.js
  appspec.yml
Labels: 배포, 서버

#147 [profile] 프로필 API 구현
  .github/workflows/continous-deploy.yml
  app/src/apis/notification/notification.ctrl.js
  app/src/apis/profile/index.js
  app/src/apis/profile/profile.ctrl.js
  app/src/apis/purchase-list/purchase-list.ctrl.js
  app/src/apis/root/root.ctrl.js
  app/src/apis/sale-list/sale-list.ctrl.js
  app/src/apis/watch-list/watch-list.ctrl.js
  app/src/models/services/Email/Email.js
  app/src/models/services/Profile/Profile.js
  app/src/models/services/PurchaseList/PurchaseList.js
  app/src/models/services/PurchaseList/PurchaseListStorage.js
  app/src/models/services/SaleList/SaleList.js
  app/src/models/services/SaleList/SaleListStorage.js
  app/src/models/services/User/User.js
  app/src/models/services/User/UserStorage.js
  app/src/models/services/WatchList/WatchList.js
  appspec.yml
  scripts/afterInstall.bash
  scripts/beforeInstall.bash
Labels: API, 기능 구현, 서버

#150 [image] image 관련 API 구현
  app/src/apis/image/image.ctrl.js
  app/src/middlewares/s3.js
  app/src/models/services/Profile/ProfileStorage.js
  app/src/models/services/WatchList/WatchListStorage.js
Labels: API, 기능 구현, 서버

#153 [Boards] 거래 완료 시 구매자 닉네임 선택으로 변경
  app/src/apis/boards/index.js
  app/src/models/services/Board/Comment/CommentStorage.js
Labels: 기능 구현

#154 [profile] 프로필 API 구현
  app/src/models/services/Profile/ProfileStorage.js
  app/src/models/services/SaleList/SaleListStorage.js
  app/src/models/services/WatchList/WatchListStorage.js
Labels: API, 기능 구현, 서버
